version: 2

sources:
  - name: staging
    database: "warehouse-450522"
    schema:   "raw_nyc_tripdata"
    tables:
      - name: external_green_tripdata
      - name: external_yellow_tripdata
      - name: external_fhv_tripdata
